### ISSUE TITLE
WGS/CDS intersect BED file looks too big

### ISSUE THREAD

**Issue by yuankunzhu** [AlexsLemonade/OpenPBTA-analysis#565] opened 2020-02-27 15:40 UTC
#### What data file(s) does this issue pertain to?
the WGS intersection bed file, `intersect_cds_lancet_strelka_mutect_WGS.bed`

and the code generated this bed
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b1b73fe321a97fa82d85c86d20bd85635aabba25/analyses/snv-callers/run_caller_consensus_analysis.sh#L66-L71

#### What release are you using?

release-v14-20200203

#### Put your question or report your issue here.
The `intersect_cds_lancet_strelka_mutect_WGS.bed` was used for the WGS TMB calculation, and 
I think the goal is to generate and use the intersection between all the caller regions and the CDS regions. Maybe we should run bedtools as below?

```
 bedtools intersect \ 
   -a data/WGS.hg38.strelka2.unpadded.bed \ 
   -b data/WGS.hg38.mutect2.vardict.unpadded.bed \ 
   | bedtools intersect -a - -b data/WGS.hg38.lancet.300bp_padded.bed \
   | bedtools intersect -a - -b $cds_file \ 
   > $coding_wgs_bed 
```

The total size of current WGS intersect bed looks too big
```
$ awk ' { sum += $3-$2 } END { print sum } ' intersect_cds_lancet_strelka_mutect_WGS.bed
3238037040
```

and it seems like it also have some overlapped regions
```
$ tail intersect_cds_lancet_strelka_mutect_WGS.bed
chrM	8365	8569
chrM	8526	9204
chrM	9206	9990
chrM	10058	10404
chrM	10469	10763
chrM	10759	12137
chrM	12336	14145
chrM	14148	14673
chrM	14746	15887
chrM	0	16569
```
we can run bedtools merge to combine those overlaps too.

**Comment by jaclyn-taroni** [comment] 2020-02-28 13:20
This issue is a duplicate of #564.

**Closed by jaclyn-taroni** 2020-02-28 13:20 UTC
Labels: data, duplicate
