### ISSUE TITLE
check pbta-snv-consensus-mutation.maf.tsv.gz for duplicated lines

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#700] opened 2020-05-20 15:29 UTC
#### What data file(s) does this issue pertain to?
pbta-snv-consensus-mutation.maf.tsv.gz

#### What release are you using?

release-v16-20200320

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#consensus-snv-calling

#### Put your question or report your issue here.
I think there are some duplicated lines in this file
 gzcat pbta-snv-consensus-mutation.maf.tsv.gz |sort|uniq -d > duplicated_lines_pbta-snv-consensus-mut.tsv
[duplicated_lines_pbta-snv-consensus-mut.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4657777/duplicated_lines_pbta-snv-consensus-mut.txt)

**Comment by jaclyn-taroni** [comment] 2020-05-20 15:45
cc @cansavvy

**Comment by cansavvy** [comment] 2020-05-20 16:10
I'll look into this today.

**Comment by jashapiro** [comment] 2020-05-20 17:50
> I also had a random question about the snv-consensus analysis , the step1 takes a metadata file https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/snv-callers/scripts/01-setup_db.py but doesn’t seem to be using it anywhere in the analysis other than making a separate metadata samples table right? Asking because we were trying to review this code to perform consensus on some new samples which don't have cleaned histology file yet

That is correct. If no metadata file is included, it simply doesn't make or update that table in the sqlite database.

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d5b13f28a82bce0f098a9c3fb808a10a8e1aef48/analyses/snv-callers/scripts/01-setup_db.py#L317

**Comment by kgaonkar6** [comment] 2020-05-20 17:52
Thanks!

**Comment by kgaonkar6** [comment] 2020-05-20 20:06
Also is it possible to have no consensus calls for a sample?  BS_C3KDA5ZC seems to be missing in pbta-snv-consensus-mutation.maf.tsv.gz

Let me know if you want this to be a different issue, thanks!

**Comment by cansavvy** [comment] 2020-05-20 20:23
> I see it in strelka,mutect2,lancet merged files.

When you say you see "it" do you mean you see the `Tumor_Sample_Barcode` in each of the strelka, mutect, and lancet files? Or you see a particular mutation for that sample that is in each file? In order for a sample to have a consensus call, the same mutation (Same "Chromosome", "Start_Position", "Reference_Allele", "Allele", "Tumor_Sample_Barcode") has to be found by each caller. So its possible a sample doesn't have any mutations that all three callers agree on.

**Comment by kgaonkar6** [comment] 2020-05-20 20:43
yeah I meant I see the Tumor_Sample_Barcode in each of the caller merged files.

Thanks for the confirmation about the bs_id!
I did a random check and seems like there are some overlaps in mutect2 and strelka2 but none overlap with lancet.

**Comment by jashapiro** [comment] 2020-05-20 20:48
Looks like at least part of the problem is with the raw data:

`gzcat data/pbta-snv-lancet.vep.maf.gz |sort|uniq -d > lancet_dups.txt`
[lancet_dups.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4659197/lancet_dups.txt)

I am running the other raw files now.

**Comment by kgaonkar6** [comment] 2020-05-20 20:53
hmm yeah that makes sense, thanks for checking

**Comment by jashapiro** [comment] 2020-05-20 21:39
The strelka and mutect files do not have full duplicates, but I can imagine there might be other duplicates that do not encompass the full row, but include the fields we had been using for indexing, namely 
```
  "Chromosome",
  "Start_Position",
  "Reference_Allele",
  "Allele",
  "Tumor_Sample_Barcode"
```

**Comment by jashapiro** [comment] 2020-05-21 01:49
After a bit further investigation, it does seem that some, but perhaps not all, of the duplicates come from `pbta-snv-lancet.vep.maf.gz`

Some that were missing from my earlier comment (based on `gzcat data/pbta-snv-lancet.vep.maf.gz |sort|uniq -d > lancet_dups.txt`) are those where for some reason there are two lines with *different allele counts* for the same genomic location, sample and alleles. 

A more complete list is here:
[lancet_duplicates.maf.tsv.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/4660175/lancet_duplicates.maf.tsv.txt)

However, this does *not* include all of the duplicates listed in the original file that @kgaonkar6 provided.

The duplications (and near-duplications) in `pbta-snv-lancet.vep.maf.gz` should be fixed for the next data release if possible #656. Tagging @yuankunzhu to coordinate that step.

We will continue to investigate to determine the origins of other remaining duplicate lines.

**Comment by jashapiro** [comment] 2020-06-12 18:40
I did some more investigation and it appears that the majority of the problems are coming from lancet. In many cases, this is because lancet is calling the same SNV with different depths, as described above. I suspect this may be due to lancet being given two overlapping regions to work with when there are nearby exons or padded SNVs that it is being used to "check", as per https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#snv-and-indel-calling

The remaining duplicates appear to also come almost entirely from lancet, but they are a bit more complicated. These are places where Lancet has made overlapping MNV calls, as illustrated here: 
<img width="1192" alt="Screen Shot 2020-06-12 at 2 26 59 PM" src="https://user-images.githubusercontent.com/20483/84535416-c60eb000-acb9-11ea-87b0-1a237219d7a7.png">

These again tend to be calls where `t_depth` varies between the overlapping calls, making me suspect they are again due to overlapping lancet regions, and not just alternate alleles.

My overall recommendation is that the lancet file `pbta-snv-lancet.vep.maf.gz` be updated to remove overlapping and duplicate calls, after which we can rerun the consensus calling to regenerate the consensus file.

It should be noted though that this is generally a quite small problem < 100 duplicate SNVs in the entire data set!

**Comment by migbro** [comment] 2020-08-12 21:41
Hi @jashapiro , I'm looking into this. In the specific example you posted, I went through the steps of re-creating the bed files used to evaluate (GENCODE CDS + mutect and strelka2 calling regions). The regions don't seem to overlap, this is an excerpt of what it would have been processing on:
```
chr10	100380894	100381109	.	500	+
chr10	100381215	100383413	.	500	+
chr10	100388033	100388361	.	500	+
chr10	100394285	100394377	.	500	+
chr10	100394497	100394622	.	500	+
chr10	100395108	100395964	.	500	+
```
also, the edge of the closest region, to the hit, `100383413`, is about 555bp away, (554 given 0-based bed file coords?), the window size is 600bp + 300bp padding, so perhaps the window ended to spilling over to the edge, causing that region to be evaluated. The next closest region in 4k+ away, so we can rule that out. I loaded the cram into IGV, and do indeed see both `GCT` and `CT` hits. Whether or not we agree that those are real is a separate question. I still need to come up with a way to efficiently grab the rest of the regions (unless you have that handy) to see if this is a one-off, but it might just be that lancet is seeing two candidate MNPs and calling them both. Hope this helps!

**Comment by jashapiro** [comment] 2020-08-13 01:25
Thanks for looking into this @migbro!
 
The full list is here: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/700#issuecomment-631830112

Is your thought that in this case the reads are extending beyond the calling region, so lancet is calling snps outside the specified regions? That does seem plausible, but I'm still confused as to why it would make two calls, often with different total read depths and depths for both reference and alt alleles. I imagine it might have to do with the local assembly that lancet does, which could end up somehow variable around the chosen regions. 

Nonetheless, the case where there are two possible alt alleles is actually the minority of the duplicates: most are identical copies of the same call. These could of course be removed very simply, but in combination with the less-trivial duplicates, they seem to point to some underlying problem during the lancet calling.

If all of the duplicates are outside of the regions that were meant to be evaluated by the given bed files, then perhaps they should be trimmed from the maf file, as I would imagine those outer regions to be more error prone in general. Of course, some of them are sneaking through to the consensus maf, so some must be confirmed by other methods. 

One other thing I'm a bit confused by now that I look at it: the regions you are showing are 500 bp, but then you say window size is 600bp + 300bp padding? Is the latter a typo? Either way, that does not quite line up with my read of [the methods](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#snv-and-indel-calling) which I had thought meant a 601 bp total window (or slightly longer for indels & MNVs). Do the methods need to be clarified? (They do need an edit, as there appears to be some redundancy in the last sentences of that section!)

**Comment by migbro** [comment] 2020-08-13 14:14
Ok, in looking at your comments, I think I can answer most questions. So, the truly duplicated MNPs and indels - in which you see the same ref/alt with same coverage repeated is as you suspect - the end of one region file, combined with the padding, overlapped with the start of the next region file (lancet jobs are split into 50, then merged afterwards) so one lancet job not knowing another lancet job has already evaluated the region is what happens. This is a known issue that has since been fixed in the pipeline - we remove the repeat entries before outputting. Your solution basically does the same and I agree it's the right and safe thing to do.
The instance I evaluated is a little trickier - Lancet did find two different overlapping MNPs, and there is read evidence; reads with all three bp, and reads with only two of the bp. To the point I brought up about going a bit beyond the interval, in the Lancet manuscript I see this:

> The algorithm starts by decomposing the whole-genome data from the input BAM files into overlapping consecutive windows of a few hundred base pairs (default 600 bp; user adjustable parameter)

This sounds like a sliding window and perhaps in this case it slide all the way to the end, and with the padding param could hit a little further than anticipated. As for the last point of confusion, I'm afraid it will always be confusing.  The 600 bp window is the same for both WGS and WXS, as well as 300bp padding. However, because the WXS input bed is padded 100bp, the _effective_ padding for WXS lancet was 400bp. I hope this helps!

**Comment by migbro** [comment] 2022-04-29 13:31
To perhaps close the one out, I think I can summarize as:
1. It’s an edge case
1. pipeline was updated to avoid this
1. Josh seemed to address this by removing duplicate lines
1. The overlapping MNPs found are probably real
1.  I think we’ve each overcome the overlapping region issue

**Closed** 2022-05-02 22:11 UTC
Labels: data
