### ISSUE TITLE
Updated analysis: chromothripsis

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1122] opened 2021-07-30 15:46 UTC
#### What analysis module should be updated and why?
chromothripsis module errors out with v20 here:

```
Evaluating the statistical criteria
Successfully finished!
[1] "Running: BS_JJNSP29S (102 of 777)"
Running..


Evaluating the statistical criteria
Error in seq.default(max(idxa), min(idxb), 1) : 
  'to' must be a finite number
Calls: shatterseek ... fmax2 -> nrow -> [ -> [.data.frame -> seq -> seq.default
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

#### What changes need to be made? Please provide enough detail for another participant to make the update.
I am not sure if it is a bug/issue with shatterseek or the cnv for BS_JJNSP29S

#### What input data should be used? Which data were used in the version being updated?
pbta-cnv-consensus.seg.gz

#### When do you expect the revised analysis will be completed?
TBD

#### Who will complete the updated analysis?
@LauraEgolf or @yangyangclover ?

**Comment by LauraEgolf** [comment] 2021-07-30 16:00
Not sure why this is happening - I'll take a look.

**Comment by kgaonkar6** [comment] 2021-07-30 17:07
Thank you!

**Comment by LauraEgolf** [comment] 2021-08-02 19:40
@kgaonkar6 I can't seem to reproduce the error from the current master branch with the latest data download - I might be missing something but the output looks fine and I'm not getting that error message. Has anything been updated since you tested this?

**Comment by LauraEgolf** [comment] 2021-08-02 20:00
Oh actually - I am still on v19. I re-ran download-data.sh but didn't realize it's still on v19. Where can I find v20? I don't see it on Cavatica. Sorry if this is obvious :)

**Comment by kgaonkar6** [comment] 2021-08-02 20:18
Ah yes, v20 download script is not pushed to master yet.

Can you clone the branch in #1118 locally and try to rerun with v20?

**Comment by jaclyn-taroni** [comment] 2021-09-13 16:15
👍🏻  thank @LauraEgolf - closing!

**Closed by jaclyn-taroni** 2021-09-13 16:15 UTC
Labels: updated analysis
